# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('mascota', models.CharField(max_length=100, verbose_name='Nombre de su mascota')),
                ('testimonio', models.CharField(max_length=200, verbose_name='Testimonio')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Testimoniales',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='oferta',
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
