# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_producto_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
